name: HACS

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  validate:
    name: HACS validation
    runs-on: ubuntu-latest
    steps:
      - name: HACS validation
        uses: hacs/action@main
        with:
          category: integration
